export interface EventInfo {
  title: string;
  category: string;
  slug: string; // Added slug for consistency with other objects
  createdAt: Date; // Changed to Date type for consistency
  author: string;
  date: Date; // Changed to Date type for consistency
  location: string;
  capacity: number;
  body: string;
  eventImageUrl: string;
  votes?: number; // Optional, since not all objects have it
}

export const eventsInfo: EventInfo[] = [
  {
    title: "Intro to Running a Node App",
    slug: "intro-to-running-a-node-app",
    category: "coding",
    author: "Sam Patel",
    body: "Learn how to get your Node.js app production-ready in this hands-on workshop for local developers. We'll explore how to run your app efficiently and reliably using systemd.",
    createdAt: new Date("2025-03-14T10:00:00Z"),
    date: new Date("2025-07-10T18:00:00Z"),
    location: "Coventry Tech Hub, CV1 2WT",
    capacity: 45,
    eventImageUrl: "https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?w=700&h=700"
  },
  {
    title: "AI in Our Community: Thinking Machines Explained",
    slug: "ai-in-our-community-thinking-machines-explained",
    category: "coding",
    author: "Leila Thompson",
    body: "Explore how AI technologies like IBM Watson are changing everyday life. Aimed at curious minds, this event breaks down complex systems into understandable insights with local use cases.",
    createdAt: new Date("2025-02-20T14:30:00Z"),
    date: new Date("2025-06-18T19:00:00Z"),
    location: "Coventry Central Library, CV1 1FY",
    capacity: 60,
    eventImageUrl: "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?w=700&h=700"
  },
  {
    title: "React Show & Tell: Open Source Projects Night",
    slug: "react-show-and-tell-open-source-projects-night",
    category: "coding",
    author: "Michael Adeyemi",
    body: "Join local developers as they showcase their favourite open source React projects. Discover tools, inspiration, and meet others passionate about frontend development.",
    createdAt: new Date("2025-01-28T17:45:00Z"),
    date: new Date("2025-06-25T18:30:00Z"),
    location: "Coventry Innovation Centre, CV1 4ET",
    capacity: 75,
    eventImageUrl: "https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?w=700&h=700"
  },
  {
    title: "Getting to Grips with Redux",
    slug: "getting-to-grips-with-redux",
    category: "coding",
    author: "Fatima Khan",
    body: "New to Redux? This workshop will help demystify the core concepts behind state management in React applications and when to use it effectively.",
    createdAt: new Date("2025-04-05T09:00:00Z"),
    date: new Date("2025-07-03T18:00:00Z"),
    location: "Coventry Digital Lab, CV1 5RN",
    capacity: 32,
    eventImageUrl: "https://images.pexels.com/photos/4974912/pexels-photo-4974912.jpeg?w=700&h=700"
  },
  {
    title: "Angular and the Future: What’s Next?",
     slug: "angular-and-the-future-whats-next",
    category: "coding",
    author: "Trevor Lin",
    body: "A relaxed evening session for developers and tech enthusiasts curious about the Angular roadmap. We'll break down the myths and facts of upcoming versions and features.",
    createdAt: new Date("2025-05-01T16:15:00Z"),
    date: new Date("2025-08-01T18:30:00Z"),
    location: "Coventry South Community Hall, CV3 6LB",
    capacity: 54,
    eventImageUrl: "https://images.pexels.com/photos/14011035/pexels-photo-14011035.jpeg?w=700&h=700"
  },
  // benchmark first five
  {
  title: "JavaScript’s Apply, Call, and Bind Methods are Essential for JavaScript Professionals",
  slug: "javascript-apply-call-bind-methods",
  category: "coding",
  author: "Samantha Lee",
  body: "Master the powerful Apply, Call, and Bind methods to write cleaner and more efficient JavaScript functions. This workshop is essential for developers aiming to deepen their understanding of function context and invocation.",
  createdAt: new Date("2025-02-15T09:30:00Z"),
  date: new Date("2025-06-10T18:00:00Z"),
  location: "Coventry Tech Hub, CV1 2WT",
  capacity: 50,
  eventImageUrl: "https://images.pexels.com/photos/4383298/pexels-photo-4383298.jpeg?w=700&h=700"
},
{
  title: "Using React Native: One Year Later",
  slug: "using-react-native-one-year-later",
  category: "coding",
  author: "David Mitchell",
  body: "Join us for a review of experiences and lessons learned after one year of developing mobile apps with React Native. We'll discuss common challenges, tips, and future trends.",
  createdAt: new Date("2025-03-01T14:45:00Z"),
  date: new Date("2025-06-20T18:30:00Z"),
  location: "Coventry Central Library, CV1 1FY",
  capacity: 40,
  eventImageUrl: "https://images.pexels.com/photos/6424586/pexels-photo-6424586.jpeg?w=700&h=700"
},
{
  title: "Express.js: A Server-Side JavaScript Framework",
  slug: "express-js-server-side-framework",
  category: "coding",
  author: "Michelle Anderson",
  body: "Discover the fundamentals of Express.js and how it simplifies server-side JavaScript development. Perfect for developers looking to build fast, scalable web apps.",
  createdAt: new Date("2025-02-10T08:00:00Z"),
  date: new Date("2025-06-25T17:00:00Z"),
  location: "Coventry Innovation Centre, CV1 4ET",
  capacity: 35,
  eventImageUrl: "https://images.pexels.com/photos/11035482/pexels-photo-11035482.jpeg?w=700&h=700"
},
{
  title: "Learn HTML5, CSS3, and Responsive WebSite Design in One Go",
  slug: "learn-html5-css3-responsive-design",
  category: "coding",
  author: "Samantha Lee",
  body: "This workshop covers the latest HTML5 and CSS3 standards and teaches you how to create responsive websites that look great on any device.",
  createdAt: new Date("2025-01-25T13:30:00Z"),
  date: new Date("2025-07-05T18:00:00Z"),
  location: "Coventry Digital Lab, CV1 5RN",
  capacity: 45,
  eventImageUrl: "https://images.pexels.com/photos/1591061/pexels-photo-1591061.jpeg?w=700&h=700"
},
{
  title: "An Introduction to JavaScript Object Notation (JSON) in JavaScript and .NET",
  slug: "introduction-json-javascript-dotnet",
  category: "coding",
  author: "Michelle Anderson",
  body: "Understand how JSON works in JavaScript and .NET environments. Learn how to parse, manipulate, and use JSON effectively in your applications.",
  createdAt: new Date("2025-02-05T10:15:00Z"),
  date: new Date("2025-07-12T18:30:00Z"),
  location: "Coventry South Community Hall, CV3 6LB",
  capacity: 30,
  eventImageUrl: "https://images.pexels.com/photos/11035481/pexels-photo-11035481.jpeg?w=700&h=700"
},
  // second five above
 {
  title: "Designing Better JavaScript APIs",
  slug: "designing-better-javascript-apis",
  category: "coding",
  author: "Eleanor Smith",
  body: "At some point or another, you will find yourself writing JavaScript code that exceeds a few lines. This workshop will guide you through designing APIs that are clean, maintainable, and user-friendly for diverse developers.",
  createdAt: new Date("2025-02-20T10:00:00Z"),
  date: new Date("2025-07-15T18:30:00Z"),
  location: "Coventry Tech Hub, CV1 2WT",
  capacity: 40,
  eventImageUrl: "https://images.pexels.com/photos/5483071/pexels-photo-5483071.jpeg?w=700&h=700"
},
{
  title: "The battle for Node.js security has only begun",
  slug: "battle-for-nodejs-security",
  category: "coding",
  author: "Ethan Williams",
  body: "Node.js security remains a critical challenge. Join us to explore common vulnerabilities and learn how to protect your applications from potential threats with practical advice from industry experts.",
  createdAt: new Date("2025-03-05T13:15:00Z"),
  date: new Date("2025-07-22T19:00:00Z"),
  location: "Coventry Innovation Centre, CV1 4ET",
  capacity: 35,
  eventImageUrl: "https://images.pexels.com/photos/10845119/pexels-photo-10845119.jpeg?w=700&h=700"
},
{
  title: "What does Jose Mourinho's handwriting say about his personality?",
  slug: "jose-mourinho-handwriting-personality",
  category: "football",
  author: "Rachel Thompson",
  body: "Explore the intriguing world of handwriting analysis with a focus on Jose Mourinho. Discover what handwriting reveals about personality and leadership styles in football management.",
  createdAt: new Date("2025-02-28T11:00:00Z"),
  date: new Date("2025-08-01T17:00:00Z"),
  location: "Coventry South Community Hall, CV3 6LB",
  capacity: 30,
  eventImageUrl: "https://images.pexels.com/photos/114296/pexels-photo-114296.jpeg?w=700&h=700"
},
{
  title: "Who Will Manage Your Club in 2021?",
  slug: "who-will-manage-your-club-2021",
  category: "football",
  author: "Oliver Green",
  body: "Managerial changes shake up the football world every season. This seminar will analyze recent changes and predict future trends in club management across English leagues.",
  createdAt: new Date("2025-02-15T09:30:00Z"),
  date: new Date("2025-08-10T18:00:00Z"),
  location: "Coventry Digital Lab, CV1 5RN",
  capacity: 40,
  eventImageUrl: "https://images.pexels.com/photos/209841/pexels-photo-209841.jpeg?w=700&h=700"
},
{
  title: "Why do England managers keep making the same mistakes?",
  slug: "england-managers-same-mistakes",
  category: "football",
  author: "Eleanor Smith",
  body: "A deep dive into the recurring challenges faced by England's football managers, exploring tactical decisions and player selections that have sparked debate among fans and experts alike.",
  createdAt: new Date("2025-01-30T14:00:00Z"),
  date: new Date("2025-08-20T18:30:00Z"),
  location: "Coventry Central Library, CV1 1FY",
  capacity: 35,
  eventImageUrl: "https://images.pexels.com/photos/262524/pexels-photo-262524.jpeg?w=700&h=700"
}
,
  // third five above
  {
  title: "FC Barcelona: Legacy and Influence Conference",
  slug: "fc-barcelona-legacy-influence-conference",
  category: "football",
  author: "Catalonia Sports Heritage Society",
  body: "Explore the rich history of FC Barcelona from its founding in 1899 to its cultural and sporting impact in Catalonia and beyond.",
  createdAt: new Date("2025-05-01T09:00:00Z"),
  date: new Date("2025-07-10T18:00:00Z"),
  location: "Coventry Sports Centre, CV1 2AB",
  capacity: 50,
  eventImageUrl: "https://images.pexels.com/photos/102448/pexels-photo-102448.jpeg?w=700&h=700"
},
{
  title: "Premier League Managers: From Players to Leaders Symposium",
  slug: "premier-league-managers-players-to-leaders",
  category: "football",
  author: "British Football Leadership Forum",
  body: "An in-depth look at the playing careers and leadership styles of current Premier League managers.",
  createdAt: new Date("2025-04-20T09:00:00Z"),
  date: new Date("2025-07-25T18:00:00Z"),
  location: "Coventry Conference Hall, CV1 4XY",
  capacity: 40,
  eventImageUrl: "https://images.pexels.com/photos/47343/the-ball-stadion-horn-corner-47343.jpeg?w=700&h=700"
},
{
  title: "Data & Analytics in Football: Tracking Every Touch Workshop",
  slug: "data-analytics-football-tracking-touch",
  category: "football",
  author: "Global Soccer Analytics Consortium",
  body: "Learn how advanced data tracking is revolutionizing the way football is played, watched, and analyzed.",
  createdAt: new Date("2025-05-10T09:00:00Z"),
  date: new Date("2025-08-05T18:00:00Z"),
  location: "Coventry Tech Hub, CV1 3QP",
  capacity: 30,
  eventImageUrl: "https://images.pexels.com/photos/1884576/pexels-photo-1884576.jpeg?w=700&h=700"
},
{
  title: "Social Media Impact on Football: Instagram’s Influence Panel",
  slug: "social-media-impact-football-instagram",
  category: "football",
  author: "Sports Digital Marketing Alliance",
  body: "Discussing the growing role of social media in football fandom, club marketing, and player branding.",
  createdAt: new Date("2025-04-28T09:00:00Z"),
  date: new Date("2025-08-20T18:00:00Z"),
  location: "Coventry Media Centre, CV1 1AA",
  capacity: 60,
  eventImageUrl: "https://images.pexels.com/photos/685382/pexels-photo-685382.jpeg?w=700&h=700"
},
{
  title: "The Origins of Football: A Historical Retrospective",
  slug: "origins-of-football-historical-retrospective",
  category: "football",
  author: "International Football History Association",
  body: "A comprehensive look at football’s origins, tracing its development from ancient games to modern sport.",
  createdAt: new Date("2025-05-05T09:00:00Z"),
  date: new Date("2025-08-30T18:00:00Z"),
  location: "Coventry Heritage Centre, CV1 5LG",
  capacity: 45,
  eventImageUrl: "https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?w=700&h=700"
},
  // fourth five above
  {
  title: "Agility Training Techniques for Football Players",
  slug: "agility-training-techniques-football",
  category: "football",
  author: "Coventry Athletic Coaching Academy",
  body: "Explore essential agility training drills designed to improve balance, speed, and injury prevention. Learn effective use of cones and ladders to elevate player performance.",
  createdAt: new Date("2020-10-26T09:45:00Z"),
  date: new Date("2025-06-15T18:00:00Z"),
  location: "Coventry Sports Centre, CV1 2AB",
  capacity: 50,
  eventImageUrl: "https://images.pexels.com/photos/3448250/pexels-photo-3448250.jpeg?w=700&h=700"
},
{
  title: "Measuring High Press Intensity: Defensive Metrics Workshop",
  slug: "measuring-high-press-intensity-defensive-metrics",
  category: "football",
  author: "British Football Analytics Institute",
  body: "An interactive workshop on developing metrics to quantify high press intensity using detailed Opta data, enabling coaches and analysts to better understand team pressing dynamics.",
  createdAt: new Date("2020-04-17T10:30:00Z"),
  date: new Date("2025-07-05T18:00:00Z"),
  location: "Coventry Conference Hall, CV1 4XY",
  capacity: 40,
  eventImageUrl: "https://images.pexels.com/photos/906073/pexels-photo-906073.jpeg?w=700&h=700"
},
{
  title: "Sunday League Football: The Grassroots Game",
  slug: "sunday-league-football-grassroots-game",
  category: "football",
  author: "Coventry Amateur Football Association",
  body: "A discussion panel on the importance of Sunday league football in the UK, covering its history, structure, and role in community engagement.",
  createdAt: new Date("2020-03-22T09:45:00Z"),
  date: new Date("2025-06-22T18:00:00Z"),
  location: "Coventry Heritage Centre, CV1 5LG",
  capacity: 60,
  eventImageUrl: "https://images.pexels.com/photos/774321/pexels-photo-774321.jpeg?w=700&h=700"
},
{
  title: "Talent Management Lessons from Elite Football Coaches",
  slug: "talent-management-lessons-football-coaches",
  category: "football",
  author: "UK Sports Leadership Forum",
  body: "An inspiring seminar examining leadership and talent management strategies used by top football coaches, with case studies including the 2012 Champions League final.",
  createdAt: new Date("2020-07-10T12:14:00Z"),
  date: new Date("2025-07-30T18:00:00Z"),
  location: "Coventry Business Hub, CV1 3QP",
  capacity: 50,
  eventImageUrl: "https://images.pexels.com/photos/168872/pexels-photo-168872.jpeg?w=700&h=700"
},
{
  title: "Roasted Vegetable Soup & Artisan Garlic Toast Workshop",
  slug: "roasted-vegetable-soup-garlic-toast-workshop",
  category: "cooking",
  author: "Coventry Culinary Arts Centre",
  body: "Learn to prepare a velvety smooth sweet potato and butternut squash soup with zesty lemon and garlic ciabatta toast in this hands-on cooking session.",
  createdAt: new Date("2020-03-11T09:56:00Z"),
  date: new Date("2025-06-05T18:00:00Z"),
  location: "Coventry Community Kitchen, CV1 1AA",
  capacity: 30,
  eventImageUrl: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?w=700&h=700"
},
{
  title: "How Cooking Has Shaped Human History",
  slug: "how-cooking-shaped-human-history",
  category: "cooking",
  author: "Coventry Archaeological Society",
  body: "Explore the fascinating archaeological discoveries revealing the origins of cooking and its role in human evolution, dating back over a million years.",
  createdAt: new Date("2020-04-06T09:00:00Z"),
  date: new Date("2025-06-20T18:00:00Z"),
  location: "Coventry Heritage Centre, CV1 5LG",
  capacity: 40,
  eventImageUrl: "https://images.pexels.com/photos/2284166/pexels-photo-2284166.jpeg?w=700&h=700"
},
{
  title: "Thanksgiving Drinks: Cocktail Mixing for All",
  slug: "thanksgiving-drinks-cocktail-mixing",
  category: "cooking",
  author: "Coventry Mixology Guild",
  body: "Celebrate Thanksgiving with a variety of delicious cocktail recipes perfect for holiday gatherings. Learn mixing techniques to impress your guests.",
  createdAt: new Date("2020-01-24T11:42:00Z"),
  date: new Date("2025-11-22T18:00:00Z"),
  location: "Coventry Event Lounge, CV1 4XY",
  capacity: 60,
  eventImageUrl: "https://images.pexels.com/photos/1565982/pexels-photo-1565982.jpeg?w=700&h=700"
},
  // here five
  {
    title: "Mastering High Altitude Cooking Techniques",
    slug: "mastering-high-altitude-cooking-techniques",
    category: "cooking",
    author: "Amy Harrison",
    body: "Most backpacking trails vary only a few thousand feet elevation. However, many trails can be found above 10,000 feet. But what many people don’t take into consideration at these high altitudes is how these elevations affect their cooking.",
    createdAt: new Date(1578097440000),
    date: new Date("2025-07-15T10:00:00Z"),
    location: "Coombe Abbey Park, Coventry",
    capacity: 35,
    eventImageUrl:
      "https://images.pexels.com/photos/691114/pexels-photo-691114.jpeg?w=700&h=700",
  },
  {
    title: "Exploring the Origins of Iconic Foods",
    slug: "exploring-the-origins-of-iconic-foods",
    category: "cooking",
    author: "Tim Cook",
    body: "In 1686, the croissant was invented in Austria. That's a fun fact I'd probably never had known or maybe don't even really need to know, but now I do, thanks to Julia Rothman's Food Anatomy: The Curious Parts & Pieces of Our Edible World. Rothman has an entire series of illustrated Anatomy books, including Nature and Farm, packed with infographics, quirky facts, and maps that you can get lost in for hours—in a fun way, not in a boring textbook way. It makes you wonder why textbooks aren't this fun to read. Can someone look into this? Thanks.",
    createdAt: new Date(1578341520000),
    date: new Date("2025-08-10T14:00:00Z"),
    location: "Coventry Transport Museum",
    capacity: 50,
    eventImageUrl:
      "https://images.pexels.com/photos/357743/pexels-photo-357743.jpeg?w=700&h=700",
  },
  {
    title: "Thanksgiving Culinary Showcase: Twice-Baked Butternut Squash",
    slug: "thanksgiving-culinary-showcase-twice-baked-butternut-squash",
    category: "cooking",
    author: "Jessica Jelly",
    body: "What if, for once, your Thanksgiving sides were just as dazzling as the centerpiece turkey? Imagine a world where presenting a platter of seasonal vegetables inspires the same amount of cooing that the turkey does. Welcome to the world of twice-baked butternut squash. Sure, you could just roast some squash wedges and call it a day. But where's the fun in that? To make this year's most impressive vegetable side, Epi's food director Rhoda Boone gave super-seasonal butternut squash the twice-baked potatoes treatment: Mash the inside of the vegetable with butter, cream, and anything else that might make it more delicious, then pile it back into the vegetable, bake it until golden and velvety. The result is a jaw-dropping, brightly colored sweet-meet-savory butternut squash side dish. Here are just a few more reasons this creation belongs on this year's Thanksgiving table:",
    createdAt: new Date(1578774000000),
    date: new Date("2025-11-25T18:00:00Z"),
    location: "The Herbert Art Gallery & Museum, Coventry",
    capacity: 60,
    eventImageUrl:
      "https://images.pexels.com/photos/175753/pexels-photo-175753.jpeg?w=700&h=700",
  },
  {
    title: "Weekly Dinner Inspirations: Fall Flavors Edition",
    slug: "weekly-dinner-inspirations-fall-flavors-edition",
    category: "cooking",
    author: "Tina Klark",
    body: "Good morning. Here’s the plan for the week, not including breakfast because I’m on a farina kick and that’s not to everyone’s taste, and not including lunch because really when it comes to the midday hours you should get out of the office or the house and walk around. If you get something to eat, great, but the most important thing is to be outside where the stories are. There’s nothing happening at your desk but a screen. Anyway! I’m thinking chicken paprikash for dinner tonight, a nod toward the coming fall, served over buttery egg noodles, with green beans on the side. If you have the time, make an apple cake for dessert.",
    createdAt: new Date(1591672740000),
    date: new Date("2025-09-05T19:30:00Z"),
    location: "Canley Community Centre, Coventry",
    capacity: 45,
    eventImageUrl:
      "https://images.pexels.com/photos/349609/pexels-photo-349609.jpeg?w=700&h=700",
  },
  {
    title: "Halal Food Integrity & Culinary Traditions Seminar",
    slug: "halal-food-integrity-culinary-traditions-seminar",
    category: "cooking",
    author: "Ahmed Karim",
    body: "CHINA’S cities abound with restaurants and food stalls catering to Muslims as well as to the many other Chinese who relish the distinctive cuisines for which the country’s Muslims are renowned. So popular are kebabs cooked by Muslim Uighurs on the streets of Beijing that the city banned outdoor grills in 2014 in order to reduce smoke, which officials said was exacerbating the capital’s notorious smog (the air today is hardly less noxious). Often such food is claimed to be qing zhen, meaning 'pure and true', or halal, prepared according to traditional Islamic regulations. But who can tell? Last year angry Muslims besieged a halal bakery in Xining, the capital of Qinghai province, after pork sausages were found in the shop’s delivery van. There have been several scandals in recent years involving rat meat or pork being sold as lamb. These have spread Muslim mistrust of domestically produced halal products.",
    createdAt: new Date(1592514480000),
    date: new Date("2025-10-12T17:00:00Z"),
    location: "Coventry Central Mosque",
    capacity: 40,
    eventImageUrl:
      "https://images.pexels.com/photos/954677/pexels-photo-954677.jpeg?w=700&h=700",
  },
  {
    title: "Tackling Seafood Fraud: Ensuring Integrity from Sea to Table",
    slug: "tackling-seafood-fraud-ensuring-integrity",
    category: "cooking",
    author: "Coventry Sustainable Seafood Alliance",
    body: "'SEAFOOD fraud is a serious global problem', begins a recent report from Oceana, an NGO. Reviewing over 200 studies in 55 countries, the report finds that one in five fish sold has been mislabelled. Although fish fraud is common early in the supply chain, most of it comes at the retail level. In 65% of cases, the motivation is economic—slippery restaurateurs frequently serve up cheaper fish than they advertise to cut costs. In America, Oceana has reported instances of tilapia being sold as the more expensive red snapper. Especially brazen fish criminals have invented new types of fish entirely. In Brazil, researchers were puzzled to find markets selling 'douradinha', ' non-existent species. Close inspection found that 60% of such fish were actually 'vulture' catfish, a relatively undesirable dish. Reports in America of catfish being substituted for more expensive fish date back to at least 2002; Oceana’s study suggests that the phenomenon is spreading.",
    createdAt: new Date(1600277160000),
    date: new Date("2025-10-01T18:00:00Z"),
    location: "Coventry Canal Basin Community Hall",
    capacity: 45,
    eventImageUrl: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?w=700&h=700",
  },
  {
    title: "MSG and the Umami Revolution: From Villain to Culinary Star",
    slug: "msg-umami-revolution-culinary-star",
    category: "cooking",
    author: "UK Culinary Science Institute",
    body: "The 'umami' craze has turned a much-maligned and misunderstood food additive into an object of obsession for the world’s most innovative chefs. But secret ingredient monosodium glutamate’s biggest secret may be that there was never anything wrong with it at all.",
    createdAt: new Date(1606043580000),
    date: new Date("2025-09-10T18:00:00Z"),
    location: "Coventry University, Herbert Art Gallery Lecture Hall",
    capacity: 55,
    eventImageUrl: "https://images.pexels.com/photos/2403392/pexels-photo-2403392.jpeg?w=700&h=700",
  },
  {
    title: "Stone Soup: Reimagining Tradition for Modern Palates",
    slug: "stone-soup-reimagining-tradition",
    category: "cooking",
    author: "Coventry Heritage Cooking Guild",
    body: "The first day I put my family on a Paleolithic diet, I made my kids fried eggs and sausage for breakfast. If they were still hungry, I told them, they could help themselves to more sausage, but they were not allowed to grab a slice of bread, or toast an English muffin, or pour themselves a bowl of cereal. This represented a reversal of the usual strictures, and they were happy to oblige. It was like some weird, unexpected holiday—Passover in July.",
    createdAt: new Date(1590477900000),
    date: new Date("2025-08-15T18:00:00Z"),
    location: "Coventry Community Kitchen",
    capacity: 30,
    eventImageUrl: "https://images.pexels.com/photos/33242/cooking-ingredient-cuisine-kitchen.jpg?w=700&h=700",
  },
  {
    title: "The Vegan Carnivore? Cultured Meat and the Future of Food",
    slug: "vegan-carnivore-cultured-meat-future",
    category: "cooking",
    author: "Innovative Food Technologies Ltd.",
    body: "The chef Richard McGeown has faced bigger culinary challenges in his distinguished career than frying a meat patty in a little sunflower oil and butter. But this time the eyes and cameras of hundreds of journalists in the room were fixed on the 5oz (140g) pink disc sizzling in his pan, one that had been five years and €250,000 in the making. This was the world’s first proper portion of cultured meat, a beef burger created by Mark Post, professor of physiology, and his team at Maastricht University in the Netherlands. Post (which rhymes with ‘lost’, not ‘ghost’) has been working on in vitro meat (IVM) since 2009. On 5 August this year he presented his cultured beef burger to the world as a ‘proof of concept’. Having shown that the technology works, Post believes that in a decade or so we could see commercial production of meat that has been grown in a lab rather than reared and slaughtered. The comforting illusion that supermarket trays of plastic-wrapped steaks are not pieces of dead animal might become a discomforting reality.",
    createdAt: new Date(1583788860000),
    date: new Date("2025-11-05T18:00:00Z"),
    location: "Coventry Innovation Hub Auditorium",
    capacity: 50,
    eventImageUrl: "https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?w=700&h=700",
  }]